import type { Achievement } from "@/components/achievment-list";
import type { Notification } from "@/components/notification-card";
import type { PerformanceData } from "@/components/performance-chart";
import type { Student } from "./components/data-table";

export const dashboardBarData = [
  { name: "School A", achievements: 1000 },
  { name: "School B", achievements: 750 },
  { name: "School C", achievements: 500 },
  { name: "School D", achievements: 1500 },
  { name: "School E", achievements: 800 },
  { name: "School F", achievements: 900 },
];

export const dashboardPieData = [
  { name: "Students", value: 10000 },
  { name: "Parents", value: 15000 },
  { name: "Achievements", value: 5000 },
];

export const schools = [
  { id: "1", label: "Springfield Elementary" },
  { id: "2", label: "Riverdale High" },
  { id: "3", label: "Sunnydale High" },
];

export const parentData = {
  name: "John Doe",
  email: "john.doe@example.com",
  profilePicture: "/placeholder.svg?height=64&width=64",
  connectedChildrenCount: 2,
  totalAchievements: 25,
};

export const connectedStudents: Student[] = [
  {
    id: "1",
    name: "Alice Doe",
    rollNo: "RH001",
    age: 16,
    std: "11",
    division: "A",
    gender: "Female",
    schoolId: "2",
    achievementsCount: 15,
  },
  {
    id: "2",
    name: "Bob Doe",
    rollNo: "SE002",
    age: 10,
    std: "5",
    division: "B",
    gender: "Male",
    schoolId: "1",
    achievementsCount: 10,
  },
];

export const achievementsData = [
  { name: "Jan", achievements: 2 },
  { name: "Feb", achievements: 5 },
  { name: "Mar", achievements: 3 },
  { name: "Apr", achievements: 7 },
  { name: "May", achievements: 8 },
];

export const studentData = {
  name: "John Doe",
  rollNumber: "STU001",
  classStandard: "10th",
  section: "A",
  totalAchievements: 15,
  averageScore: 85,
  profilePicture: "/placeholder.svg?height=100&width=100",
};

export const performanceData: PerformanceData[] = [
  { month: "Jan", score: 65 },
  { month: "Feb", score: 70 },
  { month: "Mar", score: 75 },
  { month: "Apr", score: 80 },
  { month: "May", score: 85 },
  { month: "Jun", score: 90 },
];

export const achievements: Achievement[] = [
  {
    id: "1",
    title: "Science Fair Winner",
    date: "2023-05-15",
    description:
      "First place in the annual science fair for the innovative solar energy project.",
  },
  {
    id: "2",
    title: "Perfect Attendance",
    date: "2023-06-01",
    description: "Achieved perfect attendance for the entire academic year.",
  },
  {
    id: "3",
    title: "Math Olympiad Finalist",
    date: "2023-04-22",
    description: "Qualified as a finalist in the National Math Olympiad.",
  },
];

export const notifications: Notification[] = [
  {
    id: "1",
    title: "Upcoming Parent-Teacher Meeting",
    message:
      "Please note that the Parent-Teacher meeting is scheduled for next Friday.",
    date: "2023-06-10",
    type: "info",
  },
  {
    id: "2",
    title: "Report Card Available",
    message:
      "Your quarterly report card is now available for download in the student portal.",
    date: "2023-06-05",
    type: "success",
  },
  {
    id: "3",
    title: "Library Book Overdue",
    message:
      "You have an overdue library book. Please return it as soon as possible to avoid fines.",
    date: "2023-06-02",
    type: "warning",
  },
];

export const students: Student[] = [
  {
    id: "1",
    rollNo: "SE001",
    name: "Lisa Simpson",
    age: 8,
    std: "3",
    division: "A",
    gender: "Female",
    schoolId: "1",
    achievementsCount: 15,
  },
  {
    id: "2",
    rollNo: "SE002",
    name: "Bart Simpson",
    age: 10,
    std: "5",
    division: "B",
    gender: "Male",
    schoolId: "1",
    achievementsCount: 3,
  },
  {
    id: "3",
    rollNo: "SE003",
    name: "Milhouse Van Houten",
    age: 10,
    std: "5",
    division: "B",
    gender: "Male",
    schoolId: "1",
    achievementsCount: 5,
  },
  {
    id: "10",
    rollNo: "SE005",
    name: "Maggie Simpson",
    age: 5,
    std: "1",
    division: "A",
    gender: "Female",
    schoolId: "1",
    achievementsCount: 2,
  },
  {
    id: "11",
    rollNo: "SE006",
    name: "Nelson Muntz",
    age: 11,
    std: "5",
    division: "C",
    gender: "Male",
    schoolId: "1",
    achievementsCount: 1,
  },
  // Additional Students for School 1
  {
    id: "16",
    rollNo: "SE007",
    name: "Marge Simpson",
    age: 34,
    std: "NA",
    division: "NA",
    gender: "Female",
    schoolId: "1",
    achievementsCount: 25,
  },
  {
    id: "17",
    rollNo: "SE008",
    name: "Abraham Simpson",
    age: 75,
    std: "NA",
    division: "NA",
    gender: "Male",
    schoolId: "1",
    achievementsCount: 5,
  },
  {
    id: "18",
    rollNo: "SE009",
    name: "Selma Bouvier",
    age: 50,
    std: "NA",
    division: "NA",
    gender: "Female",
    schoolId: "1",
    achievementsCount: 8,
  },
  {
    id: "19",
    rollNo: "SE010",
    name: "Patty Bouvier",
    age: 48,
    std: "NA",
    division: "NA",
    gender: "Female",
    schoolId: "1",
    achievementsCount: 7,
  },
  {
    id: "20",
    rollNo: "SE011",
    name: "Ralph Wiggum",
    age: 10,
    std: "4",
    division: "C",
    gender: "Male",
    schoolId: "1",
    achievementsCount: 3,
  },
  // School 2 (Archie Comics themed)
  {
    id: "4",
    rollNo: "RH001",
    name: "Archie Andrews",
    age: 16,
    std: "11",
    division: "A",
    gender: "Male",
    schoolId: "2",
    achievementsCount: 8,
  },
  {
    id: "5",
    rollNo: "RH002",
    name: "Betty Cooper",
    age: 16,
    std: "11",
    division: "A",
    gender: "Female",
    schoolId: "2",
    achievementsCount: 12,
  },
  {
    id: "6",
    rollNo: "RH003",
    name: "Jughead Jones",
    age: 16,
    std: "11",
    division: "B",
    gender: "Male",
    schoolId: "2",
    achievementsCount: 6,
  },
  {
    id: "12",
    rollNo: "RH004",
    name: "Veronica Lodge",
    age: 16,
    std: "11",
    division: "B",
    gender: "Female",
    schoolId: "2",
    achievementsCount: 10,
  },
  {
    id: "13",
    rollNo: "RH005",
    name: "Reggie Mantle",
    age: 16,
    std: "11",
    division: "C",
    gender: "Male",
    schoolId: "2",
    achievementsCount: 4,
  },
  // Additional Students for School 2
  {
    id: "21",
    rollNo: "RH006",
    name: "Kevin Keller",
    age: 16,
    std: "11",
    division: "B",
    gender: "Male",
    schoolId: "2",
    achievementsCount: 6,
  },
  {
    id: "22",
    rollNo: "RH007",
    name: "Dilton Doiley",
    age: 15,
    std: "10",
    division: "C",
    gender: "Male",
    schoolId: "2",
    achievementsCount: 4,
  },
  {
    id: "23",
    rollNo: "RH008",
    name: "Toni Topaz",
    age: 16,
    std: "11",
    division: "A",
    gender: "Female",
    schoolId: "2",
    achievementsCount: 7,
  },
  {
    id: "24",
    rollNo: "RH009",
    name: "Moody Spurgeon",
    age: 17,
    std: "11",
    division: "B",
    gender: "Male",
    schoolId: "2",
    achievementsCount: 3,
  },
  {
    id: "25",
    rollNo: "RH010",
    name: "Haley Jordan",
    age: 16,
    std: "11",
    division: "C",
    gender: "Female",
    schoolId: "2",
    achievementsCount: 5,
  },
  // School 3 (Buffy/Chase themed)
  {
    id: "7",
    rollNo: "SH001",
    name: "Buffy Summers",
    age: 17,
    std: "12",
    division: "A",
    gender: "Female",
    schoolId: "3",
    achievementsCount: 20,
  },
  {
    id: "8",
    rollNo: "SH002",
    name: "Willow Rosenberg",
    age: 17,
    std: "12",
    division: "A",
    gender: "Female",
    schoolId: "3",
    achievementsCount: 18,
  },
  {
    id: "9",
    rollNo: "SH003",
    name: "Xander Harris",
    age: 17,
    std: "12",
    division: "B",
    gender: "Male",
    schoolId: "3",
    achievementsCount: 7,
  },
  {
    id: "14",
    rollNo: "SH004",
    name: "Cordelia Chase",
    age: 17,
    std: "12",
    division: "B",
    gender: "Female",
    schoolId: "3",
    achievementsCount: 9,
  },
  {
    id: "15",
    rollNo: "SH005",
    name: "Spike",
    age: 18,
    std: "12",
    division: "C",
    gender: "Male",
    schoolId: "3",
    achievementsCount: 11,
  },
  // Additional Students for School 3
  {
    id: "26",
    rollNo: "SH006",
    name: "Faith Lehane",
    age: 17,
    std: "12",
    division: "B",
    gender: "Female",
    schoolId: "3",
    achievementsCount: 10,
  },
  {
    id: "27",
    rollNo: "SH007",
    name: "Dawn Summers",
    age: 16,
    std: "11",
    division: "A",
    gender: "Female",
    schoolId: "3",
    achievementsCount: 8,
  },
  {
    id: "28",
    rollNo: "SH008",
    name: "Anya Jenkins",
    age: 17,
    std: "12",
    division: "C",
    gender: "Female",
    schoolId: "3",
    achievementsCount: 6,
  },
  {
    id: "29",
    rollNo: "SH009",
    name: "Oz",
    age: 17,
    std: "12",
    division: "B",
    gender: "Male",
    schoolId: "3",
    achievementsCount: 7,
  },
  {
    id: "30",
    rollNo: "SH010",
    name: "Warren Mears",
    age: 18,
    std: "12",
    division: "C",
    gender: "Male",
    schoolId: "3",
    achievementsCount: 9,
  },
];
